version: '3.8'
services:

  parallel-completions:
    container_name: parallel-completions
    tty: true
    build: 
      context: .
    environment:
      - "OPENAI_API_KEY=${OPENAI_API_KEY:-}"
      - "OPENAI_MODEL=${OPENAI_MODEL:-}"
    volumes:
      - ./app:/app
    ports:
      - "5001:5000"
    command: flask run --host=0.0.0.0