version: '3'
services:

  parallel-completions:
    container_name: parallel-completions
    tty: true
    build: 
      context: .
    environment:
      - "OPENAI_API_KEY=${OPENAI_API_KEY:-}"
      - "OPENAI_MODEL=${OPENAI_MODEL:-}"
    volumes:
      - ./app:/app